name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: nc_news_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup test env file
        run: |
          echo "PGDATABASE=nc_news_test" >> .env.test
          echo "PGUSER=postgres" >> .env.test
          echo "PGPASSWORD=postgres" >> .env.test
          echo "PGHOST=localhost" >> .env.test
          echo "PGPORT=5432" >> .env.test

      - name: Setup database
        run: psql -h localhost -U postgres -f ./db/setup-dbs.sql
        env:
          PGPASSWORD: postgres

      - name: Run migrations/seeding
        run: npm run setup-dbs

      - name: Build (if applicable)
        run: npm run build --if-present

      - name: Run tests
        run: npm test
